version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: Events
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5436:5432"

  app:
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: Events
      ISOLATION_LEVEL: "READ COMMITTED"
      NUM_USERS: "10"  
    tty: true  
    
volumes:
  postgres-data: